[build]
builder = "dockerfile"

[deploy]
startCommand = "./App serve --env production --hostname 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
SWIFT_BACKTRACE = "enable=no"
